# Generated by Django 5.1.2 on 2026-02-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_pageview_pageviews_website_df4128_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', 'timestamp', 'path'], name='pageviews_website_5ce137_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['website', 'timestamp', 'referrer'], name='pageviews_website_f1e009_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['hash_id', 'path', 'timestamp'], name='pageviews_hash_id_01c084_idx'),
        ),
    ]
